services:
  app:
    build: .
    container_name: biogeoda_flask_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: sh /app/run.sh