"""Re-align schema and relationships after data fix and model updates

Revision ID: 88b09bd12906
Revises: d81610de407b
Create Date: 2025-06-24 08:37:23.840131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b09bd12906'
down_revision: Union[str, None] = 'd81610de407b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reserve'), 'fauna', type_='foreignkey')
    op.create_foreign_key(None, 'fauna', 'reserve', ['reserve_name'], ['reserve_name'])
    op.create_foreign_key(None, 'local_species_info', 'species', ['scientific_name'], ['scientific_name'])
    op.create_foreign_key(None, 'local_species_info', 'client_business', ['client_business_name'], ['client_business_name'])
    op.create_foreign_key(None, 'occurrences', 'species', ['scientific_name'], ['scientific_name'])
    op.create_foreign_key(None, 'occurrences', 'reserve', ['reserve_name'], ['reserve_name'])
    op.create_foreign_key(None, 'occurrences', 'client_business', ['client_business_name'], ['client_business_name'])
    op.create_foreign_key(None, 'species', 'family', ['family_name'], ['family_name'])
    op.create_foreign_key(None, 'species_trait_junction', 'species', ['scientific_name'], ['scientific_name'])
    op.create_foreign_key(None, 'species_trait_junction', 'traits', ['trait_name'], ['trait_name'])
    # FIX: Commented out the problematic alter_column for 'users.id'
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIX: Commented out the problematic alter_column for 'users.id' in downgrade as well
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_constraint(None, 'species_trait_junction', type_='foreignkey')
    op.drop_constraint(None, 'species_trait_junction', type_='foreignkey')
    op.drop_constraint(None, 'species', type_='foreignkey')
    op.drop_constraint(None, 'occurrences', type_='foreignkey')
    op.drop_constraint(None, 'occurrences', type_='foreignkey')
    op.drop_constraint(None, 'occurrences', type_='foreignkey')
    op.drop_constraint(None, 'local_species_info', type_='foreignkey')
    op.drop_constraint(None, 'local_species_info', type_='foreignkey')
    op.drop_constraint(None, 'fauna', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reserve'), 'fauna', 'reserve', ['reserve_name'], ['reserve_name'], ondelete='SET NULL')
    # ### end Alembic commands ###
