"""Add indexes for map performance

Revision ID: d81610de407b
Revises: bed0a262b001
Create Date: 2025-06-15 14:24:17.132090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd81610de407b'
down_revision: Union[str, None] = 'bed0a262b001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_occurrences')
    # Removed op.create_foreign_key for local_species_info to client_business
    # Removed op.create_foreign_key for local_species_info to species
    op.alter_column('occurrences', 'event_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # Reverted: Keeping date_identified as TEXT, removed postgresql_using
    op.alter_column('occurrences', 'date_identified',
               existing_type=sa.TEXT(), # Original type
               type_=sa.TEXT(), # Keeping as TEXT
               existing_nullable=True)
    # Removed op.create_foreign_key for occurrences to reserve
    # Removed op.create_foreign_key for occurrences to species
    # Removed op.create_foreign_key for occurrences to client_business
    op.drop_column('occurrences', 'species_name')
    op.drop_column('occurrences', 'data_source_name')
    op.alter_column('reserve', 'reserve_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # Removed op.create_foreign_key for species to family
    # Removed op.create_foreign_key for species_trait_junction to traits
    # Removed op.create_foreign_key for species_trait_junction to species
    # Removed op.alter_column for users.id
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)

    # ### BEGIN Custom Index Commands ###
    print("Creating custom indexes...")
    op.create_index('ix_occurrences_map_filters', 'occurrences',
                    ['scientific_name', 'dataset_name', 'reserve_name', 'year', 'decimal_latitude', 'decimal_longitude'],
                    unique=False)
    op.create_index('ix_local_species_info_map_filters', 'local_species_info',
                    ['scientific_name', 'planted_native'], unique=False)
    op.create_index('ix_species_exotic', 'species', ['exotic'], unique=False)
    print("Custom indexes created.")
    # ### END Custom Index Commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### BEGIN Custom Index Commands for Downgrade ###
    print("Dropping custom indexes...")
    op.drop_index('ix_species_exotic', table_name='species')
    op.drop_index('ix_local_species_info_map_filters', table_name='local_species_info')
    op.drop_index('ix_occurrences_map_filters', table_name='occurrences')
    print("Custom indexes dropped.")
    # ### END Custom Index Commands for Downgrade ###

    # Removed op.alter_column for users.id
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # Re-added op.create_foreign_key for species_trait_junction to traits
    op.create_foreign_key(None, 'species_trait_junction', 'traits', ['trait_name'], ['trait_name'])
    # Re-added op.create_foreign_key for species_trait_junction to species
    op.create_foreign_key(None, 'species_trait_junction', 'species', ['scientific_name'], ['scientific_name'])
    # Re-added op.create_foreign_key for species to family
    op.create_foreign_key(None, 'species', 'family', ['family_name'], ['family_name'])
    op.alter_column('reserve', 'reserve_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('occurrences', sa.Column('data_source_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('occurrences', sa.Column('species_name', sa.TEXT(), autoincrement=False, nullable=True))
    # Re-added op.create_foreign_key for occurrences to client_business
    op.create_foreign_key(None, 'occurrences', 'client_business', ['client_business_name'], ['client_business_name'])
    # Re-added op.create_foreign_key for occurrences to species
    op.create_foreign_key(None, 'occurrences', 'species', ['scientific_name'], ['scientific_name'])
    # Re-added op.create_foreign_key for occurrences to reserve
    op.create_foreign_key(None, 'occurrences', 'reserve', ['reserve_name'], ['reserve_name'])
    # Reverted: Keeping date_identified as TEXT in downgrade as well
    op.alter_column('occurrences', 'date_identified',
               existing_type=sa.TEXT(), # Original type
               type_=sa.TEXT(), # Keeping as TEXT
               existing_nullable=True)
    op.alter_column('occurrences', 'event_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # Re-added op.create_foreign_key for local_species_info to species
    op.create_foreign_key(None, 'local_species_info', 'species', ['scientific_name'], ['scientific_name'])
    # Re-added op.create_foreign_key for local_species_info to client_business
    op.create_foreign_key(None, 'local_species_info', 'client_business', ['client_business_name'], ['client_business_name'])
    op.create_table('temp_occurrences',
    sa.Column('scientific_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('species_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dataset_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reserve_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decimal_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('decimal_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('individual_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reproductive_condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('establishment_means', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurrence_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('habitat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sampling_protocol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('identified_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_identified', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_institution_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('basis_of_record', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_generalizations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_source_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_business_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
